# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e56c89a30b42bf1c456da13020801ade471e797114c59d119381441e4ceff332c93fa40f10d99f3036fd830991632d41e7ea53cef4e0cc041b470baf40e1fffe

test:
  secret_key_base: 5c7bd627493f2cb4d6e97b7aabddb95eef2d54dbeda54fcfaed4d2cb917c4d9513548b4d7acf1514eac35de0a8c26eb8342663e6db28bbeaf1322b06e268d761

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
